env: "local"
address: ":8080"
path:
  log_path: "../internal/utils/log/log_storage.json"
  error_path: "../internal/err/error_log.json"
  storage_path: "../db/storage.sql"

# local → твоя машина. --> LevelDebug Level = -4
	

# dev → сервер для разработчиков. --> LevelInfo  Level = 0


# staging → копия продакшена для тестов. --> LevelWarn  Level = 4


# prod → настоящий сайт или сервис. --> LevelError Level = 8

